### ISSUE TITLE
Some question about the image size

### ISSUE THREAD

**Issue by counter-clz** [yikaiw/CEN#4]
Thanks for your excellent work！I have some question about the input size of NYUDv2,
Why the processed image size is not 480 x 640 in provided NYUDv2 dataset?
and what is the AlignToMask() transformation used for in NYUDv2 and SUNRGBD dataset?

Thank you very much and look forward your reply.

**Comment by yikaiw** [comment]
Thank you for your interest. For NYUDv2, we adopt the dataset processed in https://github.com/DrSleep/light-weight-refinenet, which crops white borders of RGB and mask images. As this repo does not deal with the depth data, we use AlignToMask to crop the depth images, in order to match them with RGB or mask images. In other datasets, AlignToMask is actually not needed, because RGB, depth, and the mask already have the same shape.

**Comment by yikaiw** [comment]
Thank you for your interest. The provided NYUDv2 dataset is processed in https://github.com/DrSleep/light-weight-refinenet, which crops white borders of RGB and mask images. As this repo does not deal with the depth data, the function AlignToMask is for cropping the depth images, in order to match them with RGB or mask images. In other datasets, AlignToMask is actually not needed, because RGB, depth, and the mask already have the same shape.

**Comment by counter-clz** [comment]
Thank you for your quickly reply
